import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
import 'ng-file-upload';
import 'ng-video';
import 'mp3-cutter';
import 'datatables';
import 'jquery';
import 'angular-material';
import 'angular-animate';
import 'angular-aria';
import 'angular-messages';
// import 'bootstrap';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionality
import './layout';
import './components';
import './main/home';
import './main/basic/home';
import './main/basic/reviews';
import './main/profile';
import './services';
import './main/auth';
import './main/settings';

// Create and bootstrap application
const requires = [
    // 'mp3-cutter',
    // 'bootstrap',
    'ngMaterial',
    'ngMessages',
    'ngAria',
    'ngAnimate',
    'ui.router',
    'ngVideo',
    'ngFileUpload',
    'templates',
    'app.layout',
    'app.components',
    'app.home',
    'app.basic_home',
    'app.basic_reviews',
    'app.profile',
    'app.services',
    'app.auth',
    'app.settings'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
    strictDi: true
});
