import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
import 'ng-file-upload';
import 'ng-video';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
import './components';
import './main/home';
import './main/basic/home';
import './main/basic/reviews';
import './main/master/home';
import './main/master/dashboard';
import './main/master/archive';
import './main/master/instructor';
import './main/master/edit';
import './main/profile';
import './main/article';
import './services';
import './main/auth';
import './main/settings';
import './main/editor';

// Create and bootstrap application
const requires = [
    'ui.router',
    'ngVideo',
    'ngFileUpload',
    'templates',
    'app.layout',
    'app.components',
    'app.home',
    'app.basic_home',
    'app.basic_reviews',
    'app.master_home',
    'app.master_dashboard',
    'app.master_archive',
    'app.master_instructor',
    'app.master_edit',
    'app.profile',
    'app.services',
    'app.auth',
    'app.settings'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
    strictDi: true
});
